### ISSUE TITLE
[Calendar] Префиксный инкремент

### ISSUE THREAD

**Issue by pavel-b-novikov** [mkirichenko/nsudotnet#2]
Чем обусловлена ваша любовь к префиксному инкременту?

**Comment by mkirichenko** [comment]
Я привык так писать.

**Comment by pavel-b-novikov** [comment]
Ну вы разницу-то осознаете между префиксным и постфиксным инкрементом?

**Comment by mkirichenko** [comment]
Странный вопрос, конечно, но да, осознаю.

**Comment by pavel-b-novikov** [comment]
Это замечательно. Вот и приведите мне тогда пример кода, в котором префиксный/постфиксный инкремент будут влиять на результат.

**Comment by mkirichenko** [comment]
var a = 0;
    var b = a++; // b = 0, a = 1
    var c = ++a; // c = 2, a = 2

**Comment by pavel-b-novikov** [comment]
Окей, верю
