### ISSUE TITLE
[LinesCounter] .GetFiles

### ISSUE THREAD

**Issue by pavel-b-novikov** [mkirichenko/nsudotnet#5]
В чем разница между .GetFiles и .EnumerateFiles?

**Comment by mkirichenko** [comment]
GetFiles массив возвращает, а EnumerateFiles возвращает IEnumerable коллекцию.

**Comment by pavel-b-novikov** [comment]
А разница-то в чем? Можно сделать массив.AsEnumerable и получить то же самое. Или нет?

**Comment by mkirichenko** [comment]
Можно, конечно, только это не то же самое. В DirectoryInfo, наверное, есть какая-то внутренняя коллекция и через EnumerateFiles они отдают ее как IEnumerable, т.е. без возможности изменения. А для GetFiles они собирают ее в массив и его отдают.

**Comment by pavel-b-novikov** [comment]
То есть по-вашему отличие только в невозможности изменения?

**Comment by pavel-b-novikov** [comment]
Тук-тук?

**Comment by mkirichenko** [comment]
Спасибо, что напомнили. Я выше был не прав насчет того, что в `DirectoryInfo` есть какая-то коллекция со всеми файлами в директории и они ее отдают, на самом деле `EnumerateFiles` возвращает итератор, который делает поиск по всем файлам в директории, а `GetFiles` внутри все эти файлы положены в массив, который уже и возращается.

**Comment by pavel-b-novikov** [comment]
Вывод?

**Comment by mkirichenko** [comment]
Не понял вашего вопроса.

**Comment by pavel-b-novikov** [comment]
Какой вывод мы можете сделать из всего вышепознанного?

**Comment by mkirichenko** [comment]
Что в циклах типа `foreach (var f in dir.???Files()` разумнее использовать `EnumerateFiles`.
