### ISSUE TITLE
[Enigma] Диспоз

### ISSUE THREAD

**Issue by pavel-b-novikov** [mkirichenko/nsudotnet#7]
Ну не все же диспозится, ну..

**Comment by mkirichenko** [comment]
Убрал под `using` создание трансформов. Коммит – [1a1c4b1](https://github.com/mkirichenko/nsudotnet/commit/1a1c4b1aded3c2d52d820a5e94405fd02f0a77ef)
И зачем вы создали два ишью?

**Comment by pavel-b-novikov** [comment]
Простите, первый мне программка не показала
